# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:tvos)

platform :tvos do
  desc "Description of what the lane does"
  lane :build_simulator do
    build_app(
      skip_package_ipa: true,
      skip_archive: true,
      destination: "platform=tvOS Simulator,name=Apple TV"
  )
  end

  lane :build_unsign_ipa do
    sh "cd /Users/ho/Desktop/ATV-Bilibili-demo && rm -rf Payload *.xcarchive *.ipa *.zip"
    build_app(
    destination: "generic/platform=tvOS",
    configuration: "Release",
    codesigning_identity:"",
    skip_codesigning: true,
    skip_package_ipa: true,
    archive_path: "BilibiliLive.xcarchive",
    )
    FastlaneCore::CommandExecutor.execute(command: "cd .. && mv BilibiliLive.xcarchive/Products/Applications ./Payload")
    zip(
      path: "/Users/ho/Desktop/ATV-Bilibili-demo/Payload",
      output_path: "/Users/ho/Desktop/ATV-Bilibili-demo/BilbiliAtv"
    )
    sh "cd /Users/ho/Desktop/ATV-Bilibili-demo && mv BilbiliAtv.zip BilbiliAtv.ipa"
    sh "cd /Users/ho/Desktop/ATV-Bilibili-demo && rm -rf Payload *.xcarchive *.zip || true"
  end
end
