# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:tvos)

platform :tvos do
  project_root = File.expand_path("..", __dir__)
  output_dir = File.join(project_root, "build", "ipa")

  desc "Description of what the lane does"
  lane :build_simulator do
    build_app(
      skip_package_ipa: true,
      skip_archive: true,
      destination: "platform=tvOS Simulator,name=Apple TV"
  )
  end

  lane :build_unsign_ipa do
    sh "rm -rf '#{output_dir}' && mkdir -p '#{output_dir}'"
    build_app(
      destination: "generic/platform=tvOS",
      configuration: "Release",
      codesigning_identity: "",
      skip_codesigning: true,
      skip_package_ipa: true,
      archive_path: File.join(output_dir, "BilibiliLive.xcarchive"),
    )
    FastlaneCore::CommandExecutor.execute(
      command: "mkdir -p '#{File.join(output_dir, "Payload")}' && cp -R '#{File.join(output_dir, "BilibiliLive.xcarchive", "Products", "Applications", ".")}' '#{File.join(output_dir, "Payload")}'"
    )
    sh "test -f '#{File.join(output_dir, "Payload", "BilibiliLive.app", "Info.plist")}'"
    zip(
      path: File.join(output_dir, "Payload"),
      output_path: File.join(output_dir, "BilibiliAtv")
    )
    sh "mv '#{File.join(output_dir, "BilibiliAtv.zip")}' '#{File.join(output_dir, "BilibiliAtv.ipa")}'"
    sh "rm -rf '#{File.join(output_dir, "Payload")}' '#{File.join(output_dir, "BilibiliLive.xcarchive")}'"
  end
end
